import type { Product, ProductMedia, Suggestion } from "@/lib/types";

export const mockProducts: Product[] = [
  {
    id: "mock-1",
    name: "Modern Ribbed Desk Organizer",
    slug: "modern-ribbed-desk-organizer",
    short_description: "A premium office organizer with vertical ribbing, pen storage, and a card tray.",
    full_description:
      "A clean, high-demand desk organizer based on a real MakerWorld listing by Nils Kal. Strong Etsy direction: desk setup upgrades, office gifts, and premium two-tone print finishes.",
    category: "Desk Accessories",
    price: 34,
    etsy_url: null,
    main_image_url:
      "https://makerworld.bblmw.com/makerworld/model/USdbf99b12953d2d/design/2024-11-13_c6fc58c135d26.png?x-oss-process=image%2Fresize%2Cw_1000%2Fformat%2Cwebp",
    video_url: null,
    materials: "Matte PLA or PETG, optional two-tone rib accent",
    dimensions: "Approx. 8 in W x 3 in H x 3.25 in D",
    customization_notes: "Offer black, white, graphite, tan, and two-tone accent versions.",
    source_url: "https://makerworld.com/en/models/783651-modern-desk-organizer-low-waste-no-ams-needed",
    license_notes:
      "MakerWorld Standard Digital File License. Source page says commercial use requires permission/licensing; secure rights or make an original PRINTZ version before selling.",
    tags: ["desk", "organizer", "makerworld", "license-review"],
    featured: true,
    active: true,
    created_at: "2026-06-19T12:00:00Z",
    updated_at: "2026-06-19T12:00:00Z",
  },
  {
    id: "mock-2",
    name: "Parametric Desk Organizer Box",
    slug: "parametric-desk-organizer-box",
    short_description: "A customizable tray-and-divider organizer for desks, bathrooms, counters, and remotes.",
    full_description:
      "A flexible organizer system from MakerWorld with adjustable width, depth, height, rows, columns, dividers, tray, and front-cut options. This is a strong product direction because it can become many SKUs from one configurable model.",
    category: "Desk Accessories",
    price: 38,
    etsy_url: null,
    main_image_url:
      "https://makerworld.bblmw.com/makerworld/model/US6d9cc0286b8702/design/2025-08-01_dfe42dc14e563.jpg?x-oss-process=image%2Fresize%2Cw_1000%2Fformat%2Cwebp",
    video_url: null,
    materials: "PLA, PETG, fuzzy-skin tray finish optional",
    dimensions: "Customizable; common profile approx. 16 x 14 x 12 cm",
    customization_notes: "Sell by use case: remote holder, pen cup, bathroom organizer, kitchen caddy, or catch-all tray.",
    source_url: "https://makerworld.com/en/models/1660223-parametric-desk-organizer-fully-customizable",
    license_notes:
      "MakerWorld Standard Digital File License. Page states no commercial use without permission. Use as research, obtain rights, or build an original parametric PRINTZ model.",
    tags: ["parametric", "organizer", "desk", "customizable"],
    featured: true,
    active: true,
    created_at: "2026-06-18T12:00:00Z",
    updated_at: "2026-06-18T12:00:00Z",
  },
  {
    id: "mock-3",
    name: "Round Honeycomb Coaster Set",
    slug: "round-honeycomb-coaster-set",
    short_description: "A textured coaster set with a honeycomb insert and matching storage holder.",
    full_description:
      "A proven MakerWorld coaster listing by Anders3D with strong engagement and attractive real-user photos. This has clear Etsy potential as a giftable set, especially in bronze, charcoal, marble, and wood-look PLA.",
    category: "Decor",
    price: 26,
    etsy_url: "https://printzbykhan.etsy.com",
    main_image_url:
      "https://makerworld.bblmw.com/makerworld/model/US22513d95d744a2/design/2025-02-02_bf50b4d33da168.jpg?x-oss-process=image%2Fresize%2Cw_1000%2Fformat%2Cwebp",
    video_url: null,
    materials: "PLA or PETG; bronze/charcoal two-tone recommended",
    dimensions: "100 mm diameter coasters; holder options for 4 or 5 coasters",
    customization_notes: "Bundle as set of 4, set of 6, or coaster-plus-holder pack.",
    source_url: "https://makerworld.com/en/models/949642-round-honeycomb-coaster",
    license_notes:
      "Source page advertises a commercial license membership for selling physical prints. Join/confirm the license before listing on Etsy.",
    tags: ["coasters", "honeycomb", "gift", "makerworld"],
    featured: true,
    active: true,
    created_at: "2026-06-17T12:00:00Z",
    updated_at: "2026-06-17T12:00:00Z",
  },
  {
    id: "mock-4",
    name: "Wide Bottle Cup Holder Adapter",
    slug: "wide-bottle-cup-holder-adapter",
    short_description: "A practical car adapter for oversized bottles and tumblers.",
    full_description:
      "A functional print selected from Printables research because it solves a daily problem: large bottles and tumblers that do not fit standard car cup holders. Avoid protected brand names in the Etsy title unless permitted.",
    category: "Functional Prints",
    price: 24,
    etsy_url: "https://printzbykhan.etsy.com",
    main_image_url:
      "https://media.printables.com/media/prints/120213/images/1166547_4c1f4db2-373f-457d-817f-e886286d3263/thumbs/cover/1200x630/jpg/img_3771.jpg",
    video_url: null,
    materials: "PETG recommended for heat resistance; PLA available for indoor use",
    dimensions: "Custom bottle opening by diameter; standard car cup-holder base",
    customization_notes: "Offer custom inside diameter, vehicle-fit notes, and color options.",
    source_url: "https://www.printables.com/model/120213-hydro-flask-cup-holder-adapter",
    license_notes:
      "Printables search result reports Commercial Use and Free Cultural Works. Verify on the listing before selling and avoid trademarked brand names in listing titles.",
    tags: ["car", "adapter", "cup-holder", "printables"],
    featured: true,
    active: true,
    created_at: "2026-06-16T12:00:00Z",
    updated_at: "2026-06-16T12:00:00Z",
  },
  {
    id: "mock-5",
    name: "Snappy Dry-Erase Marker Holder",
    slug: "snappy-dry-erase-marker-holder",
    short_description: "A simple classroom and office marker holder that stores markers cap-up or cap-down.",
    full_description:
      "A practical school/office product from Printables. It is small, fast to print, and useful for teachers, tutoring rooms, offices, and home whiteboards.",
    category: "Functional Prints",
    price: 14,
    etsy_url: "https://printzbykhan.etsy.com",
    main_image_url:
      "https://media.printables.com/media/prints/8565/images/66759_d9250482-81e8-4399-b374-37ac2f6def60/thumbs/cover/1200x630/jpeg/a17760cd-bb55-409c-b118-1a9552ffb6d7_8565.jpg",
    video_url: null,
    materials: "PLA with optional adhesive strip or magnet upgrade",
    dimensions: "Modular marker slots; scale or extend based on marker count",
    customization_notes: "Sell 4-marker, 6-marker, and classroom multipack versions.",
    source_url: "https://www.printables.com/model/8565-snappy-expo-dry-erase-marker-holder",
    license_notes:
      "Printables search result reports Commercial Use and Free Cultural Works. Verify on the listing before selling.",
    tags: ["teacher", "whiteboard", "marker-holder", "printables"],
    featured: false,
    active: true,
    created_at: "2026-06-15T12:00:00Z",
    updated_at: "2026-06-15T12:00:00Z",
  },
  {
    id: "mock-6",
    name: "Inflated Bathroom Makeup Organizer",
    slug: "inflated-bathroom-makeup-organizer",
    short_description: "A soft pillow-style bathroom organizer for cosmetics, brushes, and counter clutter.",
    full_description:
      "A high-visual MakerWorld product direction from HpInvent's inflated bathroom set. Good Etsy angle: bathroom counter organization, makeup brush holder, and matching bathroom accessory sets.",
    category: "Decor",
    price: 36,
    etsy_url: null,
    main_image_url:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1200&q=80",
    video_url: null,
    materials: "Matte PLA, silk PLA, or PETG",
    dimensions: "Bathroom-counter scale; exact size depends on selected profile",
    customization_notes: "Bundle with toothbrush stand, tissue dispenser, or soap dish from the same visual family after licensing.",
    source_url: "https://makerworld.com/en/models/559513-makeup-organizer-inflated-bathroom-set",
    license_notes:
      "HpInvent pages point commercial sellers to Patreon/membership for permission. License before listing physical prints.",
    tags: ["bathroom", "makeup", "organizer", "makerworld"],
    featured: false,
    active: true,
    created_at: "2026-06-14T12:00:00Z",
    updated_at: "2026-06-14T12:00:00Z",
  },
  {
    id: "mock-7",
    name: "Dinosaur Pen Holder",
    slug: "dinosaur-pen-holder",
    short_description: "A playful dinosaur desk buddy with pencil and pen storage holes.",
    full_description:
      "A cute novelty desk product inspired by MakerWorld dinosaur pen holder listings. Good for kids, teachers, study desks, and gift bundles, but test-print before selling because some model comments mention usability and support cleanup issues.",
    category: "Desk Accessories",
    price: 22,
    etsy_url: null,
    main_image_url:
      "https://makerworld.bblmw.com/makerworld/model/US909f81076d9a24/design/2025-04-25_b4f507dd4b5e18.png?x-oss-process=image%2Fresize%2Cw_1000%2Fformat%2Cwebp",
    video_url: null,
    materials: "PLA in kid-friendly matte colors",
    dimensions: "Desk pen-holder scale; exact profile varies by model",
    customization_notes: "Offer pastel colors, teacher gift bundles, and nameplate add-ons.",
    source_url: "https://makerworld.com/en/models/973835-dinosaur-pen-holder",
    license_notes:
      "The opened MakerWorld listing shows Creative Commons Attribution-Noncommercial. Do not sell this exact model unless you receive commercial permission or create an original design.",
    tags: ["dinosaur", "pen-holder", "kids", "noncommercial"],
    featured: false,
    active: true,
    created_at: "2026-06-13T12:00:00Z",
    updated_at: "2026-06-13T12:00:00Z",
  },
  {
    id: "mock-8",
    name: "Custom Name Desk Organizer",
    slug: "custom-name-desk-organizer",
    short_description: "A personalized desk organizer with a front nameplate for gifts, teachers, and students.",
    full_description:
      "A personalization-first product direction from MakerWorld customizable name organizer listings. This is likely one of the best Etsy angles because names, colors, and roles create easy custom-order upsells.",
    category: "Custom Orders",
    price: 29,
    etsy_url: "https://printzbykhan.etsy.com",
    main_image_url:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    video_url: null,
    materials: "PLA or PETG; multi-color nameplate optional",
    dimensions: "Customizable nameplate and storage compartments",
    customization_notes: "Add name, role, short phrase, school colors, sports colors, or teacher labels.",
    source_url: "https://makerworld.com/en/models/2600234-customizable-name-desk-organizer",
    license_notes:
      "Search result suggests commercial-use context, but verify the exact MakerWorld license before selling prints.",
    tags: ["personalized", "nameplate", "teacher-gift", "custom"],
    featured: true,
    active: true,
    created_at: "2026-06-12T12:00:00Z",
    updated_at: "2026-06-12T12:00:00Z",
  },
  {
    id: "mock-9",
    name: "Modern Indoor Plant Watering Can",
    slug: "modern-indoor-plant-watering-can",
    short_description: "A sculptural watering can for houseplants, succulents, and shelf styling.",
    full_description:
      "A home-decor product direction based on Printables store listings from MODERN MACHINE/Terra de Verdant. Strong Etsy appeal because it combines utility, decor, and plant-parent gifting.",
    category: "Decor",
    price: 42,
    etsy_url: null,
    main_image_url:
      "https://media.printables.com/media/prints/926791/images/7068150_28d22501-87d2-4ee3-a6dd-68f497a3d57f_07043cf6-6059-4114-871a-c391d34689e1/thumbs/cover/1200x630/jpg/dsc05724-2.jpg",
    video_url: null,
    materials: "Watertight PETG recommended; sealed PLA prototype available for dry decor",
    dimensions: "Small indoor plant watering size; scale to target capacity",
    customization_notes: "Offer matte neutrals, translucent PETG, and matching planter bundles.",
    source_url: "https://www.printables.com/model/926791-the-nari-watering-can-for-houseplants-flowers-and",
    license_notes:
      "Source page states selling physical prints requires a commercial license membership. Join/confirm rights before listing.",
    tags: ["plants", "watering-can", "home-decor", "printables"],
    featured: false,
    active: true,
    created_at: "2026-06-11T12:00:00Z",
    updated_at: "2026-06-11T12:00:00Z",
  },
  {
    id: "mock-10",
    name: "Double-Decker Jewelry & Catch-All Box",
    slug: "double-decker-jewelry-catch-all-box",
    short_description: "A compact storage box for rings, keys, desk items, and bedside essentials.",
    full_description:
      "A compact organizer box selected because small storage products photograph well, ship easily, and fit gift/search demand. Add felt inserts or initials for higher perceived value.",
    category: "Decor",
    price: 32,
    etsy_url: "https://printzbykhan.etsy.com",
    main_image_url:
      "https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?auto=format&fit=crop&w=1200&q=80",
    video_url: null,
    materials: "PLA silk, matte PLA, or PETG; optional felt pads",
    dimensions: "Approx. 5.5 in W x 3.5 in D x 2.25 in H",
    customization_notes: "Add initials, color-matched lid, or velvet/felt insert upsells.",
    source_url: "https://www.printables.com/model/1615299-storage-box-stl-file-3d-print-double-decker-jewell",
    license_notes:
      "Search result states purchase includes commercial use rights for printing the model. Confirm terms after purchase.",
    tags: ["storage", "jewelry", "gift", "commercial-rights"],
    featured: false,
    active: true,
    created_at: "2026-06-10T12:00:00Z",
    updated_at: "2026-06-10T12:00:00Z",
  },
  {
    id: "mock-11",
    name: "Floral Paper Clip Set",
    slug: "floral-paper-clip-set",
    short_description: "Small colorful clips for planners, office gifts, classrooms, and stationery bundles.",
    full_description:
      "A low-material, fast-print stationery item inspired by Printables floral paper clip listings. Great as an Etsy add-on because it can be sold in sets, shipped cheaply, and photographed in color bundles.",
    category: "Desk Accessories",
    price: 12,
    etsy_url: "https://printzbykhan.etsy.com",
    main_image_url:
      "https://media.printables.com/media/prints/795643/images/6161806_e22c2463-f885-4814-a57f-08b6d9a4cb08_2a0f97bf-0f8a-4b76-9069-f4463681274f/thumbs/cover/1200x630/jpg/1000002966.jpg",
    video_url: null,
    materials: "PLA in assorted colors",
    dimensions: "Set of 8; approx. 1.25-1.75 in each depending on flower style",
    customization_notes: "Sell as seasonal packs, teacher gifts, planner bundles, or brand-color sets.",
    source_url: "https://www.printables.com/model/795643-floral-paper-clips",
    license_notes: "Verify Printables license before selling exact model. Easy candidate for an original PRINTZ variant.",
    tags: ["stationery", "paper-clips", "gift", "low-cost"],
    featured: false,
    active: true,
    created_at: "2026-06-09T12:00:00Z",
    updated_at: "2026-06-09T12:00:00Z",
  },
  {
    id: "mock-12",
    name: "Track Wheel Coaster Set",
    slug: "track-wheel-coaster-set",
    short_description: "Automotive-style wheel coasters for garage desks, car fans, and gift bundles.",
    full_description:
      "A coaster set based on the popularity of automotive wheel coaster models on Printables. This has strong gift appeal, but avoid protected vehicle logos, brand marks, and exact OEM wheel designs unless licensed.",
    category: "Decor",
    price: 26,
    etsy_url: "https://printzbykhan.etsy.com",
    main_image_url:
      "https://media.printables.com/media/prints/8361436c-127f-44a6-8995-e02c1623b988/images/11213038_6d8b9eb8-b3a3-4b25-b7d7-b202968e9f46_e552c24c-6aa8-4997-8d86-cfe90af7e4f2/thumbs/cover/1200x630/jpg/pxl_20251118_232220643-1.jpg",
    video_url: null,
    materials: "PLA or PETG with optional cork backing",
    dimensions: "Set of 4; approx. 3.75 in diameter",
    customization_notes: "Offer color accents, initials, and garage-themed bundles.",
    source_url: "https://www.printables.com/model/1488063-automotive-wheel-coaster-collection-multiple-oe-de",
    license_notes:
      "Check exact license and trademark/IP risk before selling. Best path is original wheel-inspired designs with no protected marks.",
    tags: ["coasters", "automotive", "gift", "trademark-review"],
    featured: false,
    active: true,
    created_at: "2026-06-08T12:00:00Z",
    updated_at: "2026-06-08T12:00:00Z",
  },
];

export const mockMedia: ProductMedia[] = mockProducts
  .filter((product) => product.main_image_url)
  .map((product, index) => ({
    id: `media-${product.id}`,
    product_id: product.id,
    media_type: "image",
    url: product.main_image_url || "",
    sort_order: index,
    created_at: product.created_at,
  }));

export const mockSuggestions: Suggestion[] = [];
