export const productImportHeaders = [
  "name",
  "slug",
  "short_description",
  "full_description",
  "category",
  "price",
  "estimated_grams",
  "estimated_print_hours",
  "tags",
  "materials",
  "dimensions",
  "color_options",
  "size_options",
  "finish_options",
  "processing_time",
  "care_instructions",
  "customization_notes",
  "personalization_enabled",
  "personalization_prompt",
  "source_url",
  "license_notes",
  "drive_media_folder_url",
  "main_image_url",
  "gallery_media_urls",
  "video_url",
  "etsy_url",
  "featured",
  "active",
  "import_status",
  "product_id",
  "site_url",
  "media_status",
  "ai_suggested_price",
  "ai_price_notes",
  "imported_at",
];

export const productImportExample = [
  "Custom Desk Organizer",
  "custom-desk-organizer",
  "Personalized 3D printed desk organizer for pens, notes, and everyday essentials.",
  "A clean, made-to-order desk organizer with optional name or initials. Add color and size notes before publishing.",
  "Desk Accessories",
  "",
  "180",
  "5",
  "desk organizer, 3d printed, custom gift",
  "PLA, PLA+",
  "Approx. 7 x 3 x 3 in",
  "Black, White, Gray, Custom Color",
  "Standard, Large",
  "Matte, Silk",
  "Made to order in 2-4 business days",
  "Keep away from high heat. Clean gently with a dry cloth.",
  "Buyer can request name, initials, color, and layout adjustments.",
  "TRUE",
  "Enter the name or initials you want added.",
  "",
  "Original PRINTZ design or approved commercial-use model.",
  "https://drive.google.com/drive/folders/EXAMPLE",
  "",
  "",
  "",
  "",
  "FALSE",
  "FALSE",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];

export function productImportTemplateCsv() {
  return [productImportHeaders, productImportExample].map((row) => row.map(csvCell).join(",")).join("\n") + "\n";
}

function csvCell(value: string) {
  return /[",\n]/.test(value) ? `"${value.replaceAll('"', '""')}"` : value;
}
