insert into public.products (
  name,
  slug,
  short_description,
  full_description,
  category,
  price,
  etsy_url,
  main_image_url,
  video_url,
  materials,
  dimensions,
  customization_notes,
  source_url,
  license_notes,
  tags,
  featured,
  active
)
values
  (
    'Modern Ribbed Desk Organizer',
    'modern-ribbed-desk-organizer',
    'A premium office organizer with vertical ribbing, pen storage, and a card tray.',
    'A clean, high-demand desk organizer direction. Request this print so PRINTZ can review model rights, printability, color, quantity, and shipping before creating a custom Etsy checkout.',
    'Desk Accessories',
    44,
    null,
    'https://makerworld.bblmw.com/makerworld/model/USdbf99b12953d2d/design/2024-11-13_c6fc58c135d26.png?x-oss-process=image%2Fresize%2Cw_1000%2Fformat%2Cwebp',
    null,
    'Matte PLA or PETG, optional two-tone rib accent',
    'Approx. 8 in W x 3 in H x 3.25 in D',
    'Request black, white, graphite, tan, or two-tone accent versions.',
    'https://makerworld.com/en/models/783651-modern-desk-organizer-low-waste-no-ams-needed',
    'Source model must be reviewed before commercial printing. PRINTZ will confirm rights or remake an original version before quoting.',
    array['desk', 'organizer', 'request print', 'makerworld'],
    true,
    true
  ),
  (
    'Parametric Desk Organizer Box',
    'parametric-desk-organizer-box',
    'A customizable tray-and-divider organizer for desks, bathrooms, counters, and remotes.',
    'A flexible organizer request that can be sized for different use cases. PRINTZ reviews dimensions, source rights, and print settings before sending a custom Etsy checkout.',
    'Desk Accessories',
    48,
    null,
    'https://makerworld.bblmw.com/makerworld/model/US6d9cc0286b8702/design/2025-08-01_dfe42dc14e563.jpg?x-oss-process=image%2Fresize%2Cw_1000%2Fformat%2Cwebp',
    null,
    'PLA, PETG, fuzzy-skin tray finish optional',
    'Customizable; common profile approx. 16 x 14 x 12 cm',
    'Request remote holder, pen cup, bathroom organizer, kitchen caddy, or catch-all tray sizing.',
    'https://makerworld.com/en/models/1660223-parametric-desk-organizer-fully-customizable',
    'Source model must be reviewed before commercial printing. PRINTZ will confirm rights or remake an original version before quoting.',
    array['parametric', 'organizer', 'request print', 'customizable'],
    true,
    true
  ),
  (
    'Inflated Bathroom Makeup Organizer',
    'inflated-bathroom-makeup-organizer',
    'A soft pillow-style bathroom organizer for cosmetics, brushes, and counter clutter.',
    'A high-visual organizer request for bathroom counters and makeup storage. PRINTZ reviews source rights and selected color/finish before quoting.',
    'Decor',
    46,
    null,
    'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1200&q=80',
    null,
    'Matte PLA, silk PLA, or PETG',
    'Bathroom-counter scale; exact size depends on selected profile',
    'Request matching bathroom accessory sets after licensing/review.',
    'https://makerworld.com/en/models/559513-makeup-organizer-inflated-bathroom-set',
    'Source model must be reviewed before commercial printing. PRINTZ will confirm rights or remake an original version before quoting.',
    array['bathroom', 'makeup', 'organizer', 'request print'],
    false,
    true
  ),
  (
    'Dinosaur Pen Holder',
    'dinosaur-pen-holder',
    'A playful dinosaur desk buddy with pencil and pen storage holes.',
    'A novelty desk product request for kids, teachers, study desks, and gift bundles. PRINTZ reviews source rights and printability before quoting.',
    'Desk Accessories',
    28,
    null,
    'https://makerworld.bblmw.com/makerworld/model/US909f81076d9a24/design/2025-04-25_b4f507dd4b5e18.png?x-oss-process=image%2Fresize%2Cw_1000%2Fformat%2Cwebp',
    null,
    'PLA in kid-friendly matte colors',
    'Desk pen-holder scale; exact profile varies by model',
    'Request pastel colors, teacher gift bundles, or nameplate add-ons.',
    'https://makerworld.com/en/models/973835-dinosaur-pen-holder',
    'The opened MakerWorld listing shows Creative Commons Attribution-Noncommercial. Do not sell this exact model unless commercial permission is granted or PRINTZ creates an original design.',
    array['dinosaur', 'pen holder', 'kids', 'request print'],
    false,
    true
  )
on conflict (slug) do update set
  short_description = excluded.short_description,
  full_description = excluded.full_description,
  price = excluded.price,
  etsy_url = excluded.etsy_url,
  main_image_url = excluded.main_image_url,
  materials = excluded.materials,
  dimensions = excluded.dimensions,
  customization_notes = excluded.customization_notes,
  source_url = excluded.source_url,
  license_notes = excluded.license_notes,
  tags = excluded.tags,
  active = excluded.active,
  updated_at = now();
