create extension if not exists pgcrypto;
create table if not exists products (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, short_description text not null, full_description text not null, category text not null, price numeric, etsy_url text, main_image_url text, video_url text, materials text, dimensions text, customization_notes text, tags text[] default '{}', featured boolean default false, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists product_media (id uuid primary key default gen_random_uuid(), product_id uuid references products(id) on delete cascade, media_type text check (media_type in ('image','video')) not null, url text not null, sort_order int default 0, created_at timestamptz default now());
create table if not exists suggestions (id uuid primary key default gen_random_uuid(), name text not null, email text not null, title text not null, description text not null, category text not null, reference_link text, budget_range text, status text default 'New' check (status in ('New','Reviewing','In Progress','Made','Rejected')), created_at timestamptz default now());
create table if not exists contact_messages (id uuid primary key default gen_random_uuid(), name text not null, email text not null, message text not null, created_at timestamptz default now());
create table if not exists admin_users (id uuid primary key default gen_random_uuid(), email text unique not null, created_at timestamptz default now());
create or replace function is_admin() returns boolean language sql stable as $$ select exists (select 1 from admin_users where lower(email)=lower(auth.jwt()->>'email')); $$;
alter table products enable row level security; alter table product_media enable row level security; alter table suggestions enable row level security; alter table contact_messages enable row level security; alter table admin_users enable row level security;
create policy "Public can read active products" on products for select using (active = true or is_admin());
create policy "Admins can manage products" on products for all using (is_admin()) with check (is_admin());
create policy "Public can read media for active products" on product_media for select using (is_admin() or exists (select 1 from products p where p.id = product_id and p.active));
create policy "Admins can manage product media" on product_media for all using (is_admin()) with check (is_admin());
create policy "Anyone can submit suggestions" on suggestions for insert with check (true);
create policy "Admins can read suggestions" on suggestions for select using (is_admin());
create policy "Admins can update suggestions" on suggestions for update using (is_admin()) with check (is_admin());
create policy "Admins can delete suggestions" on suggestions for delete using (is_admin());
create policy "Anyone can submit contact messages" on contact_messages for insert with check (true);
create policy "Admins can read contact messages" on contact_messages for select using (is_admin());
create policy "Admins can read admins" on admin_users for select using (is_admin());
insert into storage.buckets (id, name, public) values ('product-media','product-media',true) on conflict (id) do nothing;
create policy "Public media read" on storage.objects for select using (bucket_id='product-media');
create policy "Admins upload media" on storage.objects for insert with check (bucket_id='product-media' and is_admin());
create policy "Admins update media" on storage.objects for update using (bucket_id='product-media' and is_admin());
create policy "Admins delete media" on storage.objects for delete using (bucket_id='product-media' and is_admin());
